# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Fercho\Desktop\EVAPOTRANS\EVAPOTRANS\evapotrans\evotui\evotgui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(924, 585)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("img/tux.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.mdiArea = QtGui.QMdiArea(self.centralwidget)
        self.mdiArea.setEnabled(True)
        self.mdiArea.setGeometry(QtCore.QRect(0, 0, 910, 461))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.mdiArea.sizePolicy().hasHeightForWidth())
        self.mdiArea.setSizePolicy(sizePolicy)
        self.mdiArea.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mdiArea.setActivationOrder(QtGui.QMdiArea.CreationOrder)
        self.mdiArea.setViewMode(QtGui.QMdiArea.TabbedView)
        self.mdiArea.setDocumentMode(False)
        self.mdiArea.setTabShape(QtGui.QTabWidget.Rounded)
        self.mdiArea.setObjectName(_fromUtf8("mdiArea"))
        self.importtab = QtGui.QWidget()
        self.importtab.setObjectName(_fromUtf8("importtab"))
        self.eporttab = QtGui.QWidget()
        self.eporttab.setObjectName(_fromUtf8("eporttab"))
        self.layoutWidget = QtGui.QWidget(self.eporttab)
        self.layoutWidget.setGeometry(QtCore.QRect(73, 52, 352, 367))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.formLayout_2 = QtGui.QFormLayout(self.layoutWidget)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_3.addWidget(self.label_2)
        spacerItem = QtGui.QSpacerItem(20, 48, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_3.addWidget(self.label_7)
        spacerItem1 = QtGui.QSpacerItem(20, 48, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.label_8 = QtGui.QLabel(self.layoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_3.addWidget(self.label_8)
        spacerItem2 = QtGui.QSpacerItem(20, 198, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.formLayout_2.setLayout(0, QtGui.QFormLayout.LabelRole, self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.lRuta = QtGui.QLineEdit(self.layoutWidget)
        self.lRuta.setObjectName(_fromUtf8("lRuta"))
        self.horizontalLayout_5.addWidget(self.lRuta)
        self.bRuta = QtGui.QPushButton(self.layoutWidget)
        self.bRuta.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("img/open_folder.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bRuta.setIcon(icon1)
        self.bRuta.setAutoDefault(False)
        self.bRuta.setDefault(False)
        self.bRuta.setFlat(False)
        self.bRuta.setObjectName(_fromUtf8("bRuta"))
        self.horizontalLayout_5.addWidget(self.bRuta)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.lShpName = QtGui.QLineEdit(self.layoutWidget)
        self.lShpName.setObjectName(_fromUtf8("lShpName"))
        self.verticalLayout_4.addWidget(self.lShpName)
        spacerItem4 = QtGui.QSpacerItem(20, 28, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.cMetho = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cMetho.sizePolicy().hasHeightForWidth())
        self.cMetho.setSizePolicy(sizePolicy)
        self.cMetho.setObjectName(_fromUtf8("cMetho"))
        self.horizontalLayout.addWidget(self.cMetho)
        spacerItem5 = QtGui.QSpacerItem(38, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        spacerItem6 = QtGui.QSpacerItem(20, 38, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem6)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.cShp = QtGui.QCheckBox(self.layoutWidget)
        self.cShp.setObjectName(_fromUtf8("cShp"))
        self.horizontalLayout_2.addWidget(self.cShp)
        spacerItem7 = QtGui.QSpacerItem(228, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        spacerItem8 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem8)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.cExcl = QtGui.QCheckBox(self.layoutWidget)
        self.cExcl.setObjectName(_fromUtf8("cExcl"))
        self.horizontalLayout_3.addWidget(self.cExcl)
        spacerItem9 = QtGui.QSpacerItem(228, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        spacerItem10 = QtGui.QSpacerItem(20, 28, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem10)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.bExport = QtGui.QPushButton(self.layoutWidget)
        self.bExport.setObjectName(_fromUtf8("bExport"))
        self.horizontalLayout_4.addWidget(self.bExport)
        spacerItem11 = QtGui.QSpacerItem(218, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem11)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.formLayout_2.setLayout(0, QtGui.QFormLayout.FieldRole, self.verticalLayout_4)
        self.conex = QtGui.QWidget()
        self.conex.setObjectName(_fromUtf8("conex"))
        self.layoutWidget1 = QtGui.QWidget(self.conex)
        self.layoutWidget1.setGeometry(QtCore.QRect(230, 60, 301, 281))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.formLayout = QtGui.QFormLayout(self.layoutWidget1)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_3 = QtGui.QLabel(self.layoutWidget1)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_2.addWidget(self.label_3)
        spacerItem12 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem12)
        self.label_4 = QtGui.QLabel(self.layoutWidget1)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_2.addWidget(self.label_4)
        spacerItem13 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem13)
        self.label_5 = QtGui.QLabel(self.layoutWidget1)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_2.addWidget(self.label_5)
        spacerItem14 = QtGui.QSpacerItem(20, 28, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem14)
        self.label = QtGui.QLabel(self.layoutWidget1)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        spacerItem15 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem15)
        self.label_6 = QtGui.QLabel(self.layoutWidget1)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_2.addWidget(self.label_6)
        spacerItem16 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem16)
        self.bTest = QtGui.QPushButton(self.layoutWidget1)
        self.bTest.setEnabled(True)
        self.bTest.setObjectName(_fromUtf8("bTest"))
        self.verticalLayout_2.addWidget(self.bTest, QtCore.Qt.AlignTop)
        self.formLayout.setLayout(0, QtGui.QFormLayout.LabelRole, self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.lHost = QtGui.QLineEdit(self.layoutWidget1)
        self.lHost.setObjectName(_fromUtf8("lHost"))
        self.verticalLayout.addWidget(self.lHost)
        spacerItem17 = QtGui.QSpacerItem(136, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem17)
        self.lDb = QtGui.QLineEdit(self.layoutWidget1)
        self.lDb.setObjectName(_fromUtf8("lDb"))
        self.verticalLayout.addWidget(self.lDb)
        spacerItem18 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem18)
        self.lPort = QtGui.QLineEdit(self.layoutWidget1)
        self.lPort.setObjectName(_fromUtf8("lPort"))
        self.verticalLayout.addWidget(self.lPort)
        spacerItem19 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem19)
        self.lUsr = QtGui.QLineEdit(self.layoutWidget1)
        self.lUsr.setObjectName(_fromUtf8("lUsr"))
        self.verticalLayout.addWidget(self.lUsr)
        spacerItem20 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem20)
        self.lPass = QtGui.QLineEdit(self.layoutWidget1)
        self.lPass.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lPass.setEchoMode(QtGui.QLineEdit.Password)
        self.lPass.setObjectName(_fromUtf8("lPass"))
        self.verticalLayout.addWidget(self.lPass)
        spacerItem21 = QtGui.QSpacerItem(191, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem21)
        self.lSuccess = QtGui.QLabel(self.layoutWidget1)
        self.lSuccess.setText(_fromUtf8(""))
        self.lSuccess.setObjectName(_fromUtf8("lSuccess"))
        self.verticalLayout.addWidget(self.lSuccess)
        self.formLayout.setLayout(0, QtGui.QFormLayout.FieldRole, self.verticalLayout)
        self.bNext = QtGui.QPushButton(self.centralwidget)
        self.bNext.setGeometry(QtCore.QRect(46, 482, 75, 23))
        self.bNext.setObjectName(_fromUtf8("bNext"))
        self.bPrev = QtGui.QPushButton(self.centralwidget)
        self.bPrev.setGeometry(QtCore.QRect(127, 482, 75, 23))
        self.bPrev.setObjectName(_fromUtf8("bPrev"))
        self.bClose = QtGui.QPushButton(self.centralwidget)
        self.bClose.setGeometry(QtCore.QRect(208, 482, 75, 23))
        self.bClose.setObjectName(_fromUtf8("bClose"))
        self.bCas = QtGui.QPushButton(self.centralwidget)
        self.bCas.setGeometry(QtCore.QRect(46, 513, 75, 23))
        self.bCas.setObjectName(_fromUtf8("bCas"))
        self.bMos = QtGui.QPushButton(self.centralwidget)
        self.bMos.setGeometry(QtCore.QRect(127, 513, 75, 23))
        self.bMos.setObjectName(_fromUtf8("bMos"))
        self.bSub = QtGui.QPushButton(self.centralwidget)
        self.bSub.setGeometry(QtCore.QRect(208, 513, 92, 23))
        self.bSub.setObjectName(_fromUtf8("bSub"))
        self.bPes = QtGui.QPushButton(self.centralwidget)
        self.bPes.setGeometry(QtCore.QRect(306, 513, 75, 23))
        self.bPes.setObjectName(_fromUtf8("bPes"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 924, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuWindows = QtGui.QMenu(self.menubar)
        self.menuWindows.setObjectName(_fromUtf8("menuWindows"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuWindows.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Evapot Master", None))
        self.importtab.setWindowTitle(_translate("MainWindow", "Importar Info...", None))
        self.eporttab.setWindowTitle(_translate("MainWindow", "Exportar Info...", None))
        self.label_2.setText(_translate("MainWindow", "Ruta", None))
        self.label_7.setText(_translate("MainWindow", "Nombre", None))
        self.label_8.setText(_translate("MainWindow", "Metodo", None))
        self.cShp.setText(_translate("MainWindow", "Shapefile", None))
        self.cExcl.setText(_translate("MainWindow", "Excel File", None))
        self.bExport.setText(_translate("MainWindow", "Export Data", None))
        self.conex.setWindowTitle(_translate("MainWindow", "Conexión", None))
        self.label_3.setText(_translate("MainWindow", "Host:", None))
        self.label_4.setText(_translate("MainWindow", "Database:", None))
        self.label_5.setText(_translate("MainWindow", "Port:", None))
        self.label.setText(_translate("MainWindow", "User:", None))
        self.label_6.setText(_translate("MainWindow", "Password:", None))
        self.bTest.setText(_translate("MainWindow", "Test", None))
        self.bNext.setText(_translate("MainWindow", "Ver Siguiente", None))
        self.bPrev.setText(_translate("MainWindow", "Ver Previo", None))
        self.bClose.setText(_translate("MainWindow", "Cerrar Todo", None))
        self.bCas.setText(_translate("MainWindow", "Cascada", None))
        self.bMos.setText(_translate("MainWindow", "Mosaico", None))
        self.bSub.setText(_translate("MainWindow", "Vista Subventana", None))
        self.bPes.setText(_translate("MainWindow", "Vista Pestaña", None))
        self.menuWindows.setTitle(_translate("MainWindow", "Windows", None))

